# Generated by Django 5.2.6 on 2025-09-06 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakecrudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterinke',
            name='date',
            field=models.DateField(default=datetime.date(2025, 9, 6)),
        ),
    ]
