# Generated by Django 5.2.6 on 2025-09-06 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakecrudapp', '0002_alter_waterinke_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterinke',
            name='time',
            field=models.TimeField(default=datetime.time(12, 11, 33, 115539)),
        ),
    ]
